import { Montserrat } from 'next/font/google'
import './globals.css'
import Nav from '@/components/navbar/nav'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Taskify',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
